// This file was auto-generated by prisma-generator-typescript-interfaces

export type UserType = {
  id: number;
  email: string;
  name: string | null;
};

export type FeatureType = {
  id: number;
  summary: string;
  detail: string;
  createdAt: Date;
  updatedAt: Date;
};
